water=int(input("Enter the number of  water fountains.:"))
waterlocation=(input("Enter the locations for these water fountains:"))
watercondition=(input("How is the condition of the water fountains:"))
restrooms=int(input("How many restrooms are there:"))
restroomlocation=(input("Enter the locations for these restrooms:"))
restroomscondition=(input("How is the condition of the restrooms (If any are broken say how many):"))
seatingcapacity=int(input("How many seats is there capacity for in the cafeteria?:"))
dailyattendance=int(input("How many people come every day?:"))
cafeteriacondition=(input("How is the cafeteria condition?:"))
classroom=int(input("How many classrooms are there?:"))



print("WATER FOUNTAINS-----")
print(f"Number of water fountains: {water}")
print(f"Locations: {waterlocation}")
print(f"Condition: {watercondition}")
print("RESTROOMS-----")
print(f"Number of restrooms: {restrooms}")
print(f"location: {restroomlocation}")
print(f"Condition: {restroomscondition}")
print("CAFETERIA-----")
print(f"Number of seats: {seatingcapacity}")
print(f"Daily attendance: {dailyattendance}")
print(f"condition: {cafeteriacondition}")
print(f"CLASSROOMS-----")
print(f"number of classrooms: {classroom}")
print(f"Number of water fountains per class: {water/classroom}")
print(f"Number of restrooms per class: {restrooms/classroom}")

