yourname=input("What is your name?")


opponent1=input("What is the name of the first person you played?")
mypoints1=int(input("How many boxes did you get in game 1?"))
opponentpoints1=int(input("How many boxes did your opponent get in game 1?"))
boxpercent1=(f"{mypoints1/(mypoints1+opponentpoints1):.2%}")

opponent2=input("What is the name of the second person you played?")
mypoints2=int(input("How many boxes did you get in game 2?"))
opponentpoints2=int(input("How many boxes did your opponent get in game 2?"))
boxpercent2=(f"{mypoints2/(mypoints2+opponentpoints2):.2%}")

opponent3=input("What is the name of the third person you played?")
mypoints3=int(input("How many boxes did you get in game 3?"))
opponentpoints3=int(input("How many boxes did your opponent get in game 3?"))
boxpercent3=(f"{mypoints3/(mypoints3+opponentpoints3):.2%}")

opponent4=input("What is the name of the fourth person you played?")
mypoints4=int(input("How many boxes did you get in game 4?"))
opponentpoints4=int(input("How many boxes did your opponent get in game 4?"))
boxpercent4=(f"{mypoints4/(mypoints4+opponentpoints4):.2%}")

opponent5=input("What is the name of the fifth person you played?")
mypoints5=int(input("How many boxes did you get in game 5?"))
opponentpoints5=int(input("How many boxes did your opponent get in game 5?"))
boxpercent5=(f"{mypoints5/(mypoints5+opponentpoints5):.2%}")

mytotalpoints=mypoints1+mypoints2+mypoints3+mypoints4+mypoints5
opponenttotalpoints=opponentpoints1+opponentpoints2+opponentpoints3+opponentpoints4+opponentpoints5
boxtotalperc=mytotalpoints/(mytotalpoints+opponenttotalpoints)

print("Game 1:")
print(f"Opponent 1:{opponent1}")
print(f"Your points:{mypoints1}")
print(f"Opponents points:{opponentpoints1}")
print("")
print("")
print("Game 2:")
print(f"Opponent 2:{opponent2}")
print(f"Your points:{mypoints2}")
print(f"Opponents points:{opponentpoints2}")
print("")
print("")
print("Game 3:")
print(f"Opponent 3:{opponent3}")
print(f"Your points:{mypoints3}")
print(f"Opponents points:{opponentpoints3}")
print("")
print("")
print("Game 4:")
print(f"Opponent 4:{opponent4}")
print(f"Your points:{mypoints4}")
print(f"Opponents points:{opponentpoints4}")
print("")
print("")
print("Game 5:")
print(f"Opponent 5:{opponent5}")
print(f"Your points:{mypoints5}")
print(f"Opponents points:{opponentpoints5}")
print("")
print("")
print("")
print("Dots and Boxes Score Chart")
print(f"Player's name:{yourname}")
print(f"{'Opponent':<10} {'Your Points':>10} {'Opponent points':>10} {'Box%':>10}")
print("=================================================")
print(f"{opponent1:<10} {mypoints1:>11} {opponentpoints1:>15} {boxpercent1:>10}")
print(f"{opponent2:<10} {mypoints2:>11} {opponentpoints2:>15} {boxpercent2:>10}")
print(f"{opponent3:<10} {mypoints3:>11} {opponentpoints3:>15} {boxpercent3:>10}")
print(f"{opponent4:<10} {mypoints4:>11} {opponentpoints4:>15} {boxpercent4:>10}")
print(f"{opponent5:<10} {mypoints5:>11} {opponentpoints5:>15} {boxpercent5:>10}")
print("=================================================")
print("")
print("")
print("")
print("Summary:")
print(f"Total points:{mytotalpoints}")
print(f"Opponent total points:{opponenttotalpoints}")
print(f"Total box percentage:{boxtotalperc:.2%}")